### PR TITLE
Use Document Consumer Grouping

### LINKED ISSUE #3: mXDE_003: Use of Document Consumer grouping
The original mXDE chose not to group with Document Consumer, but rather chose to add the mXDE actor to the ITI-43 (Retrieve Document Set) transaction. I recommend we change to grouping with Document Consumer (possibly Content Consumer). 

I think we chose to do it this way so that the mXDE "Data Element Extractor" would not be expected to perform all the features expected of a Document Consumer. I think this is the typical Connectathon testing fear. A fear that the Connectathon monitors would force you to show user-interface features generally expected of Document Consumer. I think this is ridiculous gymnastics that we go thru in mXDE (and elsewhere) driven by our failure to define well how a Document Consumer should be tested. There are plenty of use-cases where Document Consumer is used purely by automation, if this is not testable then we need better testing.

The drawback of the current model is that it is unclear how this works with MHDS and XCA, as the editing is done to the XDS ITI-43, and not the MHDS/MHD ITI-68, or XCA ITI-39.  Had we just grouped with Document Consumer, this support by MHD and XCA would be automatic without any additional changes to mXDE. 

Further drawback is that the current model would seem to forbid use of DSUB/DSUBm... where if this was documented as a grouping with Document Consumer, this would be more open.

### PR DESCRIPTION
**Pull request by JohnMoehrke**
close #3 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed
- [x] I have selected a committee co-chair to review the PR

## ℹ Additional Information
Note that this drastically simplified the text. 
This also resulted in many of the original figures to be unnecessary or out of date. 
New diagram is from the HIE Whitepaper, or are plantuml

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
given the significant changes, this likely should have some committee time.

**Comment by JohnMoehrke** [comment]
http://build.fhir.org/ig/IHE/ITI.mXDE/branches/align-content-consumer/index.html

**Comment by JohnMoehrke** [comment]
committee reviewed the pr; agreed to accept the pr. Committee review for approval by Friday.

**Comment by JohnMoehrke** [comment]
@lukeaduncan can you approve this PR for merging?

**Review by lukeaduncan — APPROVED** [review]
Looks good.

**Comment by JohnMoehrke** [comment]
should this change the version? Version 2.0.0?

**Pull request merged**
